import type { IconNode } from 'lucide';
import {
  ArrowRight,
  Check,
  ChevronDown,
  CircleCheck,
  CircleQuestionMark,
  Clock,
  Coins,
  Compass,
  Eye,
  Flame,
  Flower2,
  Gem,
  HandHeart,
  Heart,
  Hexagon,
  Infinity as InfinityIcon,
  Mail,
  Menu,
  MessageCircle,
  Moon,
  MoonStar,
  Phone,
  PlayingCards,
  Quote,
  Send,
  Shield,
  Sparkles,
  Star,
  User,
  WandSparkles,
  X,
} from 'lucide';

export const lucideIcons = {
  'arrow-right': ArrowRight,
  check: Check,
  'chevron-down': ChevronDown,
  'circle-check': CircleCheck,
  help: CircleQuestionMark,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  eye: Eye,
  flame: Flame,
  flower: Flower2,
  gem: Gem,
  'hand-heart': HandHeart,
  heart: Heart,
  hexagon: Hexagon,
  infinity: InfinityIcon,
  mail: Mail,
  menu: Menu,
  'message-circle': MessageCircle,
  moon: Moon,
  'moon-star': MoonStar,
  phone: Phone,
  cards: PlayingCards,
  quote: Quote,
  send: Send,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  user: User,
  wand: WandSparkles,
  x: X,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof lucideIcons;
